#!/usr/bin/env python3
'''
################################################################################
#
# Make .csg files generated by OpenSCAD work with FreeCAD
#
################################################################################
'''

import json
import os
from pprint import pprint
import re
import sys


# depth-first walk function tree and return it cleaned
def traverse(fd, node, depth=0):
    for n in node['children']:
        fd.write(f"{'\t' * depth}{n['name']}({n['args']})")
        if n['children']:
            fd.write(" {\n")
            traverse(fd, n, depth+1)
            fd.write(f"{'\t' * depth}}}\n")
        else:
            fd.write(";\n")

def run(options):
    stack = []
    root = {'name': 'root', 'args': None, 'children': []}
    stack.append(root)

    with open(options['outFileName'], 'w+') as outFd:
        # build function tree
        with open(options['csgFileName'], 'r') as inFd:
            while line := inFd.readline().strip():
                if match := re.match(r'(\w+)\s*\((.*)\)\s*\{', line):
                    funcName = match.group(1)
                    args = match.group(2)
                    node = {'name': funcName, 'args': args, 'children': []}
                    stack[-1]['children'].append(node)
                    stack.append(node)
                if match := re.match(r'(\w+)\((.*)\);', line):
                    funcName = match.group(1)
                    args = match.group(2)
                    node = {'name': funcName, 'args': args, 'children': None}
                    stack[-1]['children'].append(node)
                closeCount = line.count('}')
                for _ in range(closeCount):
                    if len(stack) > 1:
                        stack.pop()
        pprint(root['children'])
        traverse(outFd, root)
    json.dump(root, sys.stdout, indent=2)

def getOps():
    #### FIXME make a proper CLI
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <csgFile> <outFile>")
        sys.exit(1)
    opts = {'csgFileName': sys.argv[1], 'outFileName': sys.argv[2], 'verbose': True}
    return opts

if __name__ == '__main__':
    opts = getOps()
    run(opts)

'''
                if not ((GROUP_PATTERN in line) and (GROUP_PATTERN in lastLine)):
                    outFd.write(line)
                lastLine = line
'''
